name: Run Node Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"  # Adjust this to your desired schedule
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  cronjob:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version you need

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: npm install

      # Step 4: Run your Node.js script (update here to index.js)
      - name: Run cron task
        run: node index.js  # Executes index.js
