name: Deploy Node.js App with Cron

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Cron Job
      run: |
        node index.js &  # Replace with your script file
        sleep 300  # Keep the job running for 5 minutes (or however long needed)
